version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  portfolio_research:
    build:
      context: .
      dockerfile: ./applications/portfolio_research/Dockerfile
    container_name: portfolio_research_service
    env_file:
      - path: .env
        required: false
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PYTHONPATH=/app/src:/app/packages/common/src
    volumes:
      - ./applications/portfolio_research/src:/app/src
      - ./packages/common/src:/app/packages/common/src
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/streamlit
      dockerfile: Dockerfile
    container_name: frontend_streamlit
    env_file:
      - path: .env
        required: false
    environment:
      - PORTFOLIO_RESEARCH_API_URL=http://portfolio_research:8000/api/v1
    volumes:
      - ./frontend/streamlit:/app
      - ./.env:/app/.env:ro
    ports:
      - "8501:8501"
    depends_on:
      - portfolio_research

volumes:
  mongo_data:
